name: Validate

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
      - name: 🏃 Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    runs-on: ubuntu-latest
    name: With HACS Action
    steps:
      - name: 🏃 HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  validate-pytest:
    runs-on: ubuntu-latest
    name: With pytest
    needs:
      - validate-hassfest
      - validate-hacs
    strategy:
      matrix:
        # HA Python versions
        #   See core/.github/workflows/ci.yaml:
        #   ALL_PYTHON_VERSIONS & DEFAULT_PYTHON*
        # ---------------------------------------
        # HA 2024.4  -> 3.12
        # HA 2024.12 -> 3.12*, 3.13
        # HA 2025.2  -> 3.13

        # hass-test-cc versions
        # ---------------------
        # --- 3.12
        # 0.13.128 -> HA 2024.6.0b4 # Removed mypy-dev
        # 0.13.129 -> HA 2024.6.0b5
        # 0.13.136 -> HA 2024.6.4
        # 0.13.148 -> HA 2024.7.4
        # 0.13.155 -> HA 2024.8.3
        # 0.13.164 -> HA 2024.9.3
        # 0.13.175 -> HA 2024.10.4
        # 0.13.181 -> HA 2024.11.0
        # 0.13.184 -> HA 2024.11.3
        # --- 3.12, 3.13
        # 0.13.195 -> HA 2024.12.5
        # 0.13.205 -> HA 2025.1.4
        # --- 3.13
        # 0.13.215 -> HA 2025.2.5
        # 0.13.224 -> HA 2025.3.3
        include:
          - hass-test-cc-version: "0.13.195"
            python-version: "3.13"
          - hass-test-cc-version: "0.13.205"
            python-version: "3.12"
          - hass-test-cc-version: "0.13.224"
            python-version: "3.13"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest-homeassistant-custom-component==${{ matrix.hass-test-cc-version }}
          pip install -r requirements.txt
      - name: 🏃 Validate with pytest
        run: |
          pytest
