name: Validate

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
      - name: 🏃 Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    runs-on: ubuntu-latest
    name: With HACS Action
    steps:
      - name: 🏃 HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  validate-pytest:
    runs-on: ubuntu-latest
    name: With pytest
    needs:
      - validate-hassfest
      - validate-hacs
    strategy:
      matrix:
        # HA Python versions
        #   See core/.github/workflows/ci.yaml:
        #   ALL_PYTHON_VERSIONS & DEFAULT_PYTHON*
        # ---------------------------------------
        # HA 2023.3 -> 3.10*, 3.11
        # HA 2023.8 -> 3.11
        # HA 2023.11 -> 3.11*, 3.12
        # HA 2024.4 -> 3.12

        # hass-test-cc versions
        # ---------------------
        # 0.13.42 -> HA 2023.7.0
        # 0.13.49 -> HA 2023.8.0
        # 0.13.109 -> HA 2024.3.3
        # 0.13.115 -> HA 2024.4.4
        # 0.13.128 -> HA 2024.6.0b4 # Removed mypy-dev
        # 0.13.129 -> HA 2024.6.0b5
        # 0.13.136 -> HA 2024.6.4
        # 0.13.148 -> HA 2024.7.4
        include:
          - hass-test-cc-version: "0.13.136"
            python-version: "3.12"
          - hass-test-cc-version: "0.13.148"
            python-version: "3.12"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest-homeassistant-custom-component==${{ matrix.hass-test-cc-version }}
          pip install -r requirements.txt
      - name: 🏃 Validate with pytest
        run: |
          pytest
